# Usar la imagen base de Python
FROM python:3.12

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos e instalar las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del frontend
COPY . .

# Comando para ejecutar la aplicación
CMD ["streamlit", "run", "app.py", "--server.port=8501"]
